name: React App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_website_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: npm install
      - name: build
        id: build
        run: npm run build
      - name: s3 deploy
        id: deploy
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_S3_STATIC_WEBISTE_ASSETS_BUCKET_NAME }} --delete
